# BakedIn System Status
# Powered by Upptime - https://upptime.js.org

owner: pantry-hash
repo: status

sites:
  # ═══════════════════════════════════════════════════════════════
  # CUSTOMER-FACING SERVICES
  # ═══════════════════════════════════════════════════════════════

  - name: Marketing Website
    url: https://bakedin.co
    icon: https://bakedin.co/favicon.png

  - name: Staging Environment
    url: https://staging.bakedin.co
    icon: https://bakedin.co/favicon.png

  # ═══════════════════════════════════════════════════════════════
  # AI INFRASTRUCTURE
  # ═══════════════════════════════════════════════════════════════

  - name: MCP Gateway
    url: https://mcp.bakedin.co/health

  - name: Research MCP
    url: https://mcp.bakedin.co/research/health

  - name: Knowledge Graph MCP
    url: https://mcp.bakedin.co/knowledge/health

  - name: CI/CD MCP
    url: https://mcp.bakedin.co/cicd/health

  - name: Dashboard MCP
    url: https://mcp.bakedin.co/dashboard/health

  - name: Context MCP
    url: https://mcp.bakedin.co/context/health

  - name: Assets MCP
    url: https://mcp.bakedin.co/assets/health

  - name: AI Investigator MCP
    url: https://mcp.bakedin.co/ai-investigator/health

# Internal services (GPU, Neptune, RDS, Security MCP) monitored via:
# - CloudWatch Dashboard: bakedin-production-overview
# - Route53 Health Checks (8 global regions)
# - 29 CloudWatch Alarms
#
# GPU Inference Server (g6.xlarge) - Not externally accessible
# Neptune Graph Database - VPC internal only
# PostgreSQL RDS - VPC internal only

status-website:
  cname: status.bakedin.co
  name: BakedIn Status

assignees:
  - glenmarkoss

commitMessages:
  commitAuthorName: "Upptime Bot"
  commitAuthorEmail: "upptime@bakedin.co"

workflowSchedule:
  graphs: "0 0 * * *"
  responseTime: "0 23 * * *"
  staticSite: "0 1 * * *"
  summary: "0 0 * * *"
  updateTemplate: "0 0 1 * *"
  uptime: "*/5 * * * *"
